kumuluzee:
  name: primerjalnik-cen-jpa
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://172.17.0.2:5432/primerjalnikcen
      username: postgres
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - entitete
      - storitve