kumuluzee:
  name: primerjalnik-cen-jpa
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://localhost:5432/primerjalnikcen
      username: postgres
      password: postgres
      max-pool-size: 20