kumuluzee:
  name: primerjalnik-cen-jpa
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PrimerjalnikCenDS
      connection-url: jdbc:postgresql://berry.db.elephantsql.com:5432/hqjhjqnw
      username: hqjhjqnw
      password: NhMtyWTE2NtDXjZAsVDNLAdfZvtsrVJW
      max-pool-size: 20
  dev:
    scan-libraries:
      - entitete
      - storitve